### PR TITLE
button switch lang

### PR DESCRIPTION
**Pull request by fahram**

### CODE REVIEW

**Comment by erikwibowo** [comment]
Great work farham. Thank you

**Comment by erikwibowo** [comment]
But one thing. If the lang source from controller. It not changing. Maybe im have to create middleware to set the lang.

**Comment by fahram** [comment]
> But one thing. If the lang source from controller. It not changing. Maybe I have to create middleware to set the lang.

iya bener, baru nyadar

**Comment by erikwibowo** [comment]
> iya bener, baru nyadar
Btw makasih bang udah berkontribusi

**Comment by erikwibowo** [comment]
> > But one thing. If the lang source from controller. It not changing. Maybe I have to create middleware to set the lang.
> 
> iya bener, baru nyadar

Maksih bang udah berkontribusi

**Pull request merged**
